name: release_drafter
on:
  push:
    tags:
      - 1.0.*
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Merged:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
