---
services:
  jenkins:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: jenkins
    ports:
      - 80:8080
      - 8022:22
    # volumes:
    #   - jenkins_data:/var/jenkins_home
    depends_on:
      - jenkins-agent
  jenkins-agent:
    build:
      context: .
      dockerfile: ./Dockerfile.agent
    image: jenkins-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
# volumes:
#   jenkins_data:
